version: "3.7"
services:
  db:
    container_name: myemr-db
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:?Please set the USER_ID variable}
        GROUP_ID: ${GROUP_ID:?Please set the GROUP_ID variable}
    ports:
      - "5152:3306"
    volumes:
      - type: bind
        source: ${MYEMR_DATADIR:?Please set the MYEMR_DATADIR variable}/db
        target: /var/lib/mysql
    user: ${USER_ID}:${GROUP_ID}
  web:
    depends_on:
      - db
    container_name: myemr-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:?Please set the USER_ID variable}
        GROUP_ID: ${GROUP_ID:?Please set the GROUP_ID variable}
    ports:
      - "5151:5001"
    volumes:
      - type: bind
        source: ${MYEMR_DATADIR:?Please set the MYEMR_DATADIR variable}/videos
        target: /myemr/data/videos
    command: ["./wait-for-it.sh", "db:3306", "--", "./myemr"]
    user: ${USER_ID}:${GROUP_ID}
