version: "3"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: myemr-db
    volumes:
      - ${DATADIR}/db:/var/lib/mysql
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: myemr-web
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ${DATADIR}/videos:/myemr/data/videos
    command: ["./wait-for-it.sh", "db:3306", "--", "./myemr"]