version: "3"
services:
  db:
    image: mariadb:10.5.5
    container_name: myemr-db
    environment:
      - MYSQL_DATABASE=myemr
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data/db:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myemr-web
    environment:
      - MYSQL=myemr-db
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./data/videos:/myemr/data/videos
    command: ["./wait-for-it.sh", "db:3306", "--", "./myemr"]